version: "3.9"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgress_user
      POSTGRES_PASSWORD: postgress_password
      POSTGRES_DB: books
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
  app1:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: books
      DB_USER: postgress_user
      DB_PASSWORD: postgress_password
      DB_HOST: db
      DB_PORT: 5432

  app2:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: books
      DB_USER: postgress_user
      DB_PASSWORD: postgress_password
      DB_HOST: db
      DB_PORT: 5432
  nginx:
    image: nginx
    ports:
      - "8500:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata:
