apiVersion: apps/v1
kind: Deployment
metadata:
  name: netsoft
  namespace: netsoft
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: netsoft
  template:
    metadata:
      labels:
        app: netsoft
    spec:
      containers:
        - name: netsoft
          image: {{ .Values.deployment.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "books"
            - name: DB_USER
              value: "postgress_user"
            - name: DB_PASSWORD
              value: "postgress_password"

        - name: netsoft-db
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgress_user"
            - name: POSTGRES_PASSWORD
              value: "postgress_password"
            - name: POSTGRES_DB
              value: "books"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: node-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: node-storage
          hostPath:
            path: /var/postgrsql_data
            type: DirectoryOrCreate
