apiVersion: v1
kind: Service
metadata:
  name: netsoft
  namespace: netsoft
spec:
  selector:
    app: netsoft
  ports:
    - port: 80
      targetPort: 
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: netsoft
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432