apiVersion: apps/v1
kind: Deployment
metadata:
  name: netsoft
  namespace: netsoft
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: netsoft
  template:
    metadata:
      labels:
        app: netsoft
    spec:
      containers:
        - name: netsoft
          image: {{.Values.deployment.image}}
          ports:
            - containerPort: 80