apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netsoft
  namespace: netsoft
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - service.finik.publicvm.com
      secretName: service.finik-publicvm-com-tls
  rules:
    - host: service.finik.publicvm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netsoft
                port:
                  number: 80