name: CI

on:
  push:
    #tags: ["v*"]
    branches: ["*"]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read
      packages: write

    runs-on: my-runners

    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
      image_full: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    steps:
      - name: Copy repo to runner
        uses: actions/checkout@v4        

      - name: Log in ghcr.io
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{env.REGISTRY}} 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create labels and tags for docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
      - name: Build and push docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          echo $KUBECONFIG
          whoami
          echo $HOME
          cd ~/
          ls
          mkdir -p ~/.kube
          echo "${{secrets.KUBECONFIG}}" > ~/.kube/config
          chmod 600 ~/.kube/config
          cat /home/runner/.kube/config

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        run: |
          helm upgrade --install netsoft ./netsoft \
            --namespace netsoft --create-namespace \
            --set image="${{ needs.build.outputs.image_full }}:${{ needs.build.outputs.image_tag }}"